# Generated by Django 4.0.2 on 2022-04-06 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=200)),
                ('technology', models.CharField(max_length=100)),
                ('estimatedHours', models.IntegerField()),
                ('startDate', models.DateField(null=True)),
                ('completionDate', models.DateField(null=True)),
            ],
            options={
                'db_table': 'project',
            },
        ),
        migrations.CreateModel(
            name='Project_team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appraisall_tracking.project')),
            ],
            options={
                'db_table': 'project_team',
            },
        ),
        migrations.CreateModel(
            name='Project_module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moduleName', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=30)),
                ('estimatedHours', models.IntegerField()),
                ('startDate', models.DateField()),
                ('completionDate', models.DateField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appraisall_tracking.project')),
            ],
            options={
                'db_table': 'project_module',
            },
        ),
    ]
